name: nf-core CI
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on: [push, pull_request]

jobs:
  test:
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['19.10.0', '']
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      #- name: Pull docker image (Cant pull standard single image for this pipeline as we are using individual containers)
      #  run: |
      #    docker pull nfcore/imcyto:dev
      #    docker tag nfcore/imcyto:dev nfcore/imcyto:1.0.0
      - name: Run the pipeline with .mcd input
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker

  parameters:
    env:
      NXF_VER: '19.10.0'
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parameters: [--skip_ilastik]
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      #- name: Pull docker image (Cant pull standard single image for this pipeline as we are using individual containers)
      #  run: |
      #    docker pull nfcore/imcyto:dev
      #    docker tag nfcore/imcyto:dev nfcore/imcyto:1.0.0
      - name: Run pipeline with various options
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker ${{ matrix.parameters }}

  config:
    env:
      NXF_VER: '19.10.0'
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [test_txt, test_tiff]
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      #- name: Pull docker image (Cant pull standard single image for this pipeline as we are using individual containers)
      #  run: |
      #    docker pull nfcore/imcyto:dev
      #    docker tag nfcore/imcyto:dev nfcore/imcyto:1.0.0
      - name: Run pipeline with various test configs
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile ${{ matrix.config }},docker
